### ISSUE TITLE
Upgrade to v5

### ISSUE THREAD

**Issue by just-dodo** [capacitor-community/contacts#104]
https://capacitorjs.com/docs/next/updating/plugins/5-0

**Comment by tafelnl** [comment]
As soon as Capacitor v5 is production ready, I'll update the plugin to support it!

**Comment by Paso** [comment]
Capacitor 5.0.0 has been released now.

**Comment by tafelnl** [comment]
Great. I'll ship a release next week. Again, for the ones in a hurry: I _think_ you _should_ be able to use v4 of this plugin in an app running on the Capacitor v5 version. But please report if that isn't the case. I haven't had the time to verify so myself.

**Comment by drekinov** [comment]
v4 works (so far) if you add namespace to gradle.bundle file because AGP v8 refuse to compile even if single capacitor plugin is not having namespace.
that is kind of fine workaround for testing but it is better to have all change released before doing any production release.
I eventually used fork but did workaround for sentry-capacitor - testing purposes only

**Comment by tafelnl** [comment]
Thanks for reporting. V5 will be shipped next week, so stay tuned!

**Comment by tafelnl** [comment]
Released as beta ([v5.0.0-beta.1](https://www.npmjs.com/package/@capacitor-community/contacts/v/5.0.0-beta.1)).

Should be very stable though. Nothing has changed except for running the `npx @capacitor/plugin-migration-v4-to-v5@latest` command.

Run `npm install @capacitor-community/contacts@beta` to upgrade.

**Comment by tafelnl** [comment]
Everything has been working fine since the v5 beta release. So I promoted it to production! Can be installed using `npm install @capacitor-community/contacts@latest`. Closing this issue
