### ISSUE TITLE
Is there any way to detect changes in contacts?

### ISSUE THREAD

**Issue by prakash03yes** [capacitor-community/contacts#62]
Is there any way to detect changes in contacts? , Need to re sync contacts when changes made in contacts!

**Comment by tafelnl** [comment]
In my opinion, this would be out of scope for this plugin. AFAIK, unfortunately, both Android and iOS do not have an API to detect changes in the contact list.

First thing that comes to my mind, is to do something like this:

Query all contacts and make a hash of the full list (without the IDs, because they are subject to change, unfortunately!). Then save that hash somewhere. Consequently you can check regularly if the hash will change if you re-generate it from the full list of contacts queried. If it does, most likely a contact has been updated or a new one has been added.
