### ISSUE TITLE
Running Gradle build - failed! [capacitor] [error] - July 2022

### ISSUE THREAD

**Issue by erikjmartinez** [capacitor-community/contacts#76]
When trying to run my app with this plugin as well as the example application (https://github.com/byrdsandbytes/capContactsDemo) i get the following errors when running 'ionic capacitor run android'.

Running Gradle build - failed!
[capacitor] [error] 
 * What went wrong:
[capacitor]         A problem occurred configuring project ':capacitor-community-contacts'.
[capacitor]         > Could not resolve all artifacts for configuration ':capacitor-community-contacts:classpath'.
[capacitor]         > Could not resolve org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.61.

I ran the following commands before trying to run the application  on android.

- npm install
- ionic run build
- ionic cap sync

**Comment by tafelnl** [comment]
Because of the age of this issue, I'll close it. But if you do still encounter issues, please re-open.

---

On a side note:

A new major of this plugin just got released as a beta version. The plugin is refactored quite a bit. Among others, the API and TypeScript definitions got improved.

Check out the newly added docs here: https://capacitor-community.github.io/contacts

Mind you that the new version (v3 and v4) are currently still in beta. However, the beta is tested quite extensively and fairly stable. If you're willing to test it out in your project, it would be much appreciated!
